version: "3"
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=alexandria
      # following option is a must to configure on production system:
      # https://hub.docker.com/_/postgres
      # - POSTGRES_PASSWORD=
    volumes:
      - dbdata:/var/lib/postgresql/data
  alexandria:
    image: ghcr.io/projectcaluma/alexandria:dev
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    environment:
      - DATABASE_HOST=db
      # following options are a must to configure on production system:
      # https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-SECRET_KEY
      # - SECRET_KEY=
      # https://docs.djangoproject.com/en/2.1/ref/settings/#allowed-hosts
      # - ALLOWED_HOSTS=
      # https://docs.djangoproject.com/en/2.1/ref/settings/#password
      # same as postgres password above
      # - DATABASE_PASSWORD=
  minio:
    image: minio/minio:RELEASE.2023-11-06T22-26-08Z
    volumes:
      - minio_data:/data
      - /tmp/.minio:/root/.minio  # for certificates
    ports:
      - "443:443"
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ROOT_USER=very
      - MINIO_ROOT_PASSWORD=secret
    command: server data --console-address ":9090"
  mc:
    image: minio/mc:RELEASE.2023-11-06T04-19-23Z
    restart: on-failure
    environment:
      - MINIO_ROOT_USER=very
      - MINIO_ROOT_PASSWORD=secret
    # You might need to override the entrypoint in docker-compose.override.yml to reflect your setup
    entrypoint: >
      /bin/sh -c "
      mc config host add dc-minio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} --api S3v4;
      mc mb dc-minio/alexandria-media;"
    depends_on:
      - minio

volumes:
  dbdata:
  minio_data:
    driver: local
